language: python

services:
  - docker

cache:
  directories:
    - /root/.cache/pip
    - /root/.cargo

before_install:
  - docker build -t davidblewett/rure-python:$TRAVIS_COMMIT .

notifications:
  email: false

script:
  - docker run davidblewett/rure-python:$TRAVIS_COMMIT /bin/sh -c "python -m unittest discover -s /root/rure/tests"
